### ISSUE TITLE
Adminrights evaluation

### ISSUE THREAD

**Issue by stephannn** [amakvana/EzYuzu#1]
Hi there,
you wrote that the app requires admin rights in case of missing dependencies. Have you thought about just use runas to restart the app in case it is required. Some people (me eg.;)) fell uncomfortable running every app as admin. In another app I do it his way:

        [SupportedOSPlatform("windows")]
        public static bool checkUac()
        {
            WindowsPrincipal pricipal = new WindowsPrincipal(WindowsIdentity.GetCurrent());
            return pricipal.IsInRole(WindowsBuiltInRole.Administrator);
        }

        [SupportedOSPlatform("windows")]
        public static void runUac()
        {

            if (!checkUac())
            {
                ProcessStartInfo startInfo = new ProcessStartInfo();
                startInfo.UseShellExecute = true;
                startInfo.WorkingDirectory = Environment.CurrentDirectory;
                startInfo.FileName = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
                startInfo.Verb = "runas";
                try
                {
                    Process p = Process.Start(startInfo);
                    Environment.Exit(0);
                }
                catch (Exception e)
                {
                    Console.WriteLine("Error UAC: " + e.Message);
                    System.Diagnostics.Debug.WriteLine("This utility requires elevated priviledges to complete correctly.", "Error: UAC Authorisation Required");
                }
            }

        }

**Comment by MrSandMan123** [comment]
Help guys I accidentally pressed new install id there a way to retrieve the old files?

**Comment by amakvana** [comment]
Closed - Added in v1.6.0.0
https://github.com/amakvana/EzYuzu/releases/latest
