### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by buruto** [amakvana/EzYuzu#12]
**Is your feature request related to a problem? Please describe.**

EzYuzu v1.4.0.0 currently does not show any change log when there is a new update available for Yuzu.

**Describe the solution you'd like**

I would like that the next version of EzYuzu after v1.4.0.0 (I guess v1.5.0.0) will show change log when there is a new update available for Yuzu **if possible**.

If not then you can close this but let me know why before you close this and explain why.

**Describe alternatives you've considered**

An alternative is to view the Yuzu changelogs elsewhere on the internet using any internet browser like Microsoft Edge, Google Chrome, Mozilla Firefox, Opera and etc. 

**Additional context**

A changelog is a list of changes that the update does.
In this list the user can see what was added to Yuzu, what was removed from Yuzu and what was modified in Yuzu and etc.

**Comment by amakvana** [comment]
Within the yuzu-mainline repo, I haven't found a changelog consisting of "user friendly" changes. 

Yuzu releases are automated and so is their set of changes made. The changes made are in usually in response to merge requests or under-the-hood tweaks, so I'm not sure how beneficial this would be for a typical end user. 

Have a look below and you'll see what I mean:
https://github.com/yuzu-emu/yuzu-mainline/releases

**Comment by buruto** [comment]
> Within the yuzu-mainline repo, I haven't found a changelog consisting of "user friendly" changes. The only area I know of is their `progress reports`, which are published once a month, at the end of each month (these can be found [here](https://yuzu-emu.org/entry/))
> 
> Yuzu releases are published automatically and their set of changes made are also automatically generated. The changes made are typically in response to merge requests or under-the-hood tweaks, so I'm not sure how beneficial this would be for the traditional end user.
> 
> Have a look below and you'll see what I mean: https://github.com/yuzu-emu/yuzu-mainline/releases

So you are saying that this is possible but does not worth the effort and time because this is not so useful.

Did I understand you correctly?

**Comment by amakvana** [comment]
What I am saying is that, the typical end user probably won't understand what changes (like the following picture below) actually mean:

![image](https://user-images.githubusercontent.com/66264136/210150660-cafe8590-04cf-42d9-95f3-458624bbffb9.png)

It would be possible to pull these changes down, I would need to rewrite some code to grab the changes section, but I don't think the user would benefit from this as the messages are very verbose and not "user friendly"

**Comment by buruto** [comment]
> What I am saying is that, the typical end user probably won't understand what changes (like the following picture below) actually mean:
> 
> ![image](https://user-images.githubusercontent.com/66264136/210150660-cafe8590-04cf-42d9-95f3-458624bbffb9.png)
> 
> It would be possible to pull these changes down, I would need to rewrite some code to grab the changes section, but I don't think the user would benefit from this as the messages are very verbose and not "user friendly"

And there isn't better place that explain these change logs better?

**Comment by amakvana** [comment]
> And there is no better place that explain these change logs better? Are you really sure about this?

I haven't found anywhere that does explain these changelogs better, however, you're more than welcome to have a look. If you do find something, let me know

**Comment by buruto** [comment]
> > And there is no better place that explain these change logs better? Are you really sure about this?
> 
> I haven't found anywhere that does explain these changelogs better, however, you're more than welcome to have a look. If you do find something, let me know

I will update you if I find something interesting.

**Comment by amakvana** [comment]
That's fine. In the meantime, I will close this and if you do find anything, open another Issue and we can take it from there
