### ISSUE TITLE
Works it in experimental versions?

### ISSUE THREAD

**Issue by Milor123** [amakvana/EzYuzu#13]
I want use it for update experimental version > (https://github.com/pineappleEA/pineapple-src), Works? the other problems not work.

**Comment by amakvana** [comment]
Have you tried using their updater? See the website below:

https://pineappleea.github.io/

**Comment by amakvana** [comment]
Closed - Added to v1.5.0.0
https://github.com/amakvana/YuzuModDownloader/releases/latest
