### ISSUE TITLE
Ezyuzu Version No Longer Supported Error Msg

### ISSUE THREAD

**Issue by shajman** [amakvana/EzYuzu#14]
Downloaded latest version of EzYuzu. Deleted old version. Extracted to folder.

Keep getting 'This version of EzYuzu is no longer supported' msg.

![EzYuzu](https://user-images.githubusercontent.com/52754330/210178838-f28d645a-4a6e-4996-b2ee-ba2d8748dacf.png)

**Comment by amakvana** [comment]
I've just downloaded the latest version, unzipped, ran it and it loads fine. You may need to clear your Cache in your browsers 

Did you download it from the following link below?
https://github.com/amakvana/EzYuzu/releases/tag/v1.4.0.0

**Comment by shajman** [comment]
> I've just downloaded the latest version, unzipped, ran it and it loads fine. You may need to clear your Cache in your browsers
> 
> Did you download it from the following link below? https://github.com/amakvana/EzYuzu/releases/tag/v1.4.0.0

Yes the same. Just downloaded it again now from above link to make sure and same error message.

**Comment by amakvana** [comment]
The only URL EzYuzu connects to is the URL below and that's to check the version
https://raw.githubusercontent.com/amakvana/EzYuzu/master/version

Can you confirm you can access this directly? 

Also try this:
1. Start > search for `inetcpl.cpl` and open it
2. In the `General` tab, click `Delete`. Select everything except `Preserve favourites website data` and click `Delete`
3. In the `Security` tab, click on `Reset all zones to default level`
4. In the `Content` tab, click on `Clear SSL state`
5. In the `Advanced` tab, click on `Restore advanced settings`
6. Click `Apply` > `OK`

Confirm back

**Comment by shajman** [comment]
> The only URL EzYuzu connects to is the URL below and that's to check the version https://raw.githubusercontent.com/amakvana/EzYuzu/master/version
> 
> Can you confirm you can access this directly?
> 
> Ensure the latest .NET Framework is installed
> 
> Also try this:
> 
>     1. Start > search for `inetcpl.cpl` and open it
> 
>     2. In the `General` tab, click `Delete`. Select everything except `Preserve favourites website data` and click `Delete`
> 
>     3. In the `Security` tab, click on `Reset all zones to default level`
> 
>     4. In the `Content` tab, click on `Clear SSL state`
> 
>     5. In the `Advanced` tab, click on `Restore advanced settings`
> 
>     6. Click `Apply` > `OK`
> 
> 
> Confirm back

Sorry about the late reply. I just got to test it now.

Realized my ControlD DNS was blocking raw.github for some reason. Added it to whitelist and all ok now,

Sorry about that and thanks for the support.

**Comment by BoscoDomingo** [comment]
I had the same issue and it turns out Nord VPN was the problem. Leaving it here for future reference!

**Comment by EclipseSSK** [comment]
> 

Thank you! Yes, Nord VPN seems to cause this error.
