### ISSUE TITLE
Add feature to rollback to a specific/previous version after update.

### ISSUE THREAD

**Issue by Nicolas-Miranda** [amakvana/EzYuzu#16]
**Is your feature request related to a problem? Please describe.**
As YUZU is in constant development and sometimes things break for some games. It would be useful if EzYuzu can store the previous version installed so if a new update is available and is not stable, users can go back to the previous version.

**Describe the solution you'd like**
For example:

- A user has installed the Mainline build 1388 with stable features and after some weeks he opens EzYuzu and an update is available to Mainline Build 1407 (It would also be useful to display the build version that is being updated: currentBuildNumber -> newBuildNumber in the "Update Yuzu" button)
- After the update the user finds that the emulator is unstable and he opens EzYuzu and from the menu bar selects Options->Previous Versions, Clicks on the last one Mainline Build1388 and it's reinstalled.
- For this feature to work EzYuzu should keep track of at least 1 installed build number so it can be appended to the GitHub URL and be able to download it: https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-{buildNumber}

**Describe alternatives you've considered**
Another way to implement this feature could be to include an input field for the build number so EzYuzu can download it and install it.

**Additional context**

**Comment by amakvana** [comment]
I had never even considered implementing rollback, however, that does make plenty of sense and would come in handy for definite, so thank you.

I'll draft something up soon and begin implementing a rollback feature that works seamlessly between Mainline and EA branches! 

I'm currently working on adding Steam Deck support for YuzuModDownloader.

**Comment by amakvana** [comment]
Closed - Added in v1.6.0.0
https://github.com/amakvana/EzYuzu/releases/latest

**Comment by Nicolas-Miranda** [comment]
@amakvana thanks so much for adding this feature. I truly appreciate your dedication to this project!!!!

Thanks so very much!!!
