### ISSUE TITLE
Run with command line

### ISSUE THREAD

**Issue by miapuffia** [amakvana/EzYuzu#17]
**Is your feature request related to a problem? Please describe.**
I have multiple instances of yuzu from multiple switches I've ripped, so it's inconvenient to select the folder and update each one. I like to stay on the latest version so I'm constantly updating.

**Describe the solution you'd like**
If EzYuzu supported running from the command line with flags for at least install path, I could easily run that command and launch that instance of yuzu all from one batch file in one click.

**Describe alternatives you've considered**
EzYuzu could support updating multiple installs which would be convenient enough.

**Additional context**
None. Thanks for an amazing app

**Comment by miapuffia** [comment]
I really want this feature so I'll take a crack at implementing it!

**Comment by amakvana** [comment]
Sorry! I haven't ignored this! I had attempted this ages ago but then life took over and I completely forgot about it 😂 

I have an idea how to implement it, but will add a few command line switch options to be able to switch update channels, etc.

**Comment by miapuffia** [comment]
No worries! I've actually made a lot of progress implementing it myself.
When the PR is ready you can compare to what you already had. Thanks

**Comment by miapuffia** [comment]
I got a PR in last night. Take a look when you get a chance.

**Comment by miapuffia** [comment]
I'm writing some tests and I'm a bit confused, why does YuzuManager need to delete the yuzu/config folder from the user/appdata/roaming folder?

**Comment by miapuffia** [comment]
In the branch detector code, "yuzu-cmd-exe --version" is used to detect the branch. That works for early-access but for mainline it's not.
![image](https://user-images.githubusercontent.com/6520363/235565413-281ff322-410d-4dc8-9c9e-6d29ca3d7a43.png)

**Comment by amakvana** [comment]
> I'm writing some tests and I'm a bit confused, why does YuzuManager need to delete the yuzu/config folder from the user/appdata/roaming folder?

Just in case there is some broken configuration files, it removes them all before pulling fresh copies

> In the branch detector code, "yuzu-cmd-exe --version" is used to detect the branch. That works for early-access but for mainline it's not. It seems like it doesn't want to exit unless I force it to manually. It ends up returning None for the branch.

I have noticed the newest version doesn't close itself, however, the Branch still returns as Mainline as the output stream is read in and the comparison is made against it. I've just done an update, then forced updated again by deleting the `version` file and all seems well?

**Comment by miapuffia** [comment]
I figured it the issue. The testing framework I'm using, NUnit, isn't
respecting the redirectStandardOutput of yuzu-cmd-exe. That's not a problem
with EzYuzu.

**Comment by amakvana** [comment]
Closed - Added in v1.6.0.0
https://github.com/amakvana/EzYuzu/releases/latest
