### ISSUE TITLE
Equivalent for Citra

### ISSUE THREAD

**Issue by John-Enigma** [amakvana/EzYuzu#18]
Can a equivalent of this program be plausibly made for Citra, the 3DS emulator?

**Comment by amakvana** [comment]
Is there nothing like this for Citra at all? Haven't messed about with that emulator yet

**Comment by John-Enigma** [comment]
> Is there nothing like this for Citra at all? Haven't messed about with that emulator yet

None, [as far as I know](https://citra-emu.org/download/#).

There's literally no portable version.

**Comment by amakvana** [comment]
Closed - Citra Project has ended
