### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by informagico** [amakvana/EzYuzu#20]
**Is your feature request related to a problem? Please describe.**
Please provide .editorconfig file so it is easier to contribute.

**Describe the solution you'd like**
Add .editorconfig file to the repo.

**Comment by amakvana** [comment]
Sure thing, I will compile one through Visual Studio and upload it with the next update of EzYuzu. Will keep this open until I've pushed the next update

**Comment by amakvana** [comment]
Closed - Added in v1.6.0.0
https://github.com/amakvana/EzYuzu/releases/latest
