### ISSUE TITLE
Add option to use as launcher. Not just updater

### ISSUE THREAD

**Issue by Xarishark** [amakvana/EzYuzu#21]
Add option to instantly run yuzu after verifying that there is no update. 
That way we can shortcut EzYuzu to desktop instead of yuzu itself. So, we can run and update it from the same shortcut.

Run EzYuzu -> Check for update -> Update to latest channel version -> run yuzu
or 
Run EzYuzu -> Check for update -> No update found -> run yuzu

A button to run yuzu in general would be very useful too.

**Comment by amakvana** [comment]
Didn't even think of this. Should be easy enough, so will add this into the next release! Thanks for the suggestions!

**Comment by Xarishark** [comment]
Super happy to help. If you want a good example check the primehack updater. it does exactly that. Updates the dolphin emulator it uses if there is an update otherwise it runs the game instantly. that way you dont even see the updater unless you have to update.

**Comment by amakvana** [comment]
Closed - Added in v1.6.0.0
https://github.com/amakvana/EzYuzu/releases/latest
