### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by buthig666** [amakvana/EzYuzu#26]
**Describe the bug**
I am using on a 4k screen and can't see the menu buttons or resize the window.  I have tried disabling full screen optimizations and toggled through all of the high dpi settings.
![Screenshot (1)](https://github.com/amakvana/EzYuzu/assets/67175138/8731f00d-6660-4f9f-a761-c5e475f6bab9)

**To Reproduce**
just running it

**Expected behavior**
to resize the window so I can see the menu and other options 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 11

**Additional context**
4k screen, latest nvidia drivers, rtx 4080

**Comment by Spyke8x** [comment]
Experiencing the same scaling issue also on win 11 however my screen is a 16:10 2560x1600

**Comment by YoLolo69** [comment]
Same visual bug for me, Net 7 updated, 4K screen.

**Comment by mjd180** [comment]
Same - 4k device/1920x1080 res/150% scale (recommended)

**Comment by amakvana** [comment]
Could you guys try the build attached to this comment and report back? @buthig666 @mjd180 @Spyke8x @YoLolo69 

Instead of hard-coding the Height and Offset values, I've changed it to dynamically calculate it based on drawn height

Let me know if this resolves, or if the same issues persist.

[EzYuzu_TestBuild.zip](https://github.com/amakvana/EzYuzu/files/11555354/EzYuzu_TestBuild.zip)

**Comment by YoLolo69** [comment]
It's deleted by Windows Defender :(
![Capture d’écran (666)](https://github.com/amakvana/EzYuzu/assets/104314631/c1c32324-7117-45bc-afda-ea1e9b023561)

**Comment by mjd180** [comment]
> Could you guys try the build attached to this comment and report back? @buthig666 @mjd180 @Spyke8x @YoLolo69
> 
> Instead of hard-coding the Height and Offset values, I've changed it to dynamically calculate it based on drawn height
> 
> Let me know if this resolves, or if the same issues persist.
> 
> [EzYuzu_TestBuild.zip](https://github.com/amakvana/EzYuzu/files/11555354/EzYuzu_TestBuild.zip)

Scalng fixed/Thanks!

**Comment by amakvana** [comment]
> It's deleted by Windows Defender :( ![Capture d’écran (666)](https://user-images.githubusercontent.com/104314631/240656653-c1c32324-7117-45bc-afda-ea1e9b023561.png)

False positive, go into Defender and add an exception for now. See VirusTotal scan below 

https://github.com/amakvana/EzYuzu/issues/28

**Comment by amakvana** [comment]
> > Could you guys try the build attached to this comment and report back? @buthig666 @mjd180 @Spyke8x @YoLolo69
> > Instead of hard-coding the Height and Offset values, I've changed it to dynamically calculate it based on drawn height
> > Let me know if this resolves, or if the same issues persist.
> > [EzYuzu_TestBuild.zip](https://github.com/amakvana/EzYuzu/files/11555354/EzYuzu_TestBuild.zip)
> 
> Scalng fixed/Thanks!

Thanks for reporting back!

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.1.0
https://github.com/amakvana/EzYuzu/releases/latest
