### ISSUE TITLE
New version 1.6 detected as a trojan in Windows Defender

### ISSUE THREAD

**Issue by JacobDrivers** [amakvana/EzYuzu#28]
**Describe the bug**
Windows Defender has flagged EzYuzu as a "TrojanScript/Wacatac.H!ml"

**To Reproduce**
1. Download or try to open EzYuzu
4. See the error

**Screenshots**
![Screenshot 2023-05-24 113525](https://github.com/amakvana/EzYuzu/assets/44545600/72cb9e22-7264-4177-a683-a7ea4c98dc63)

**Desktop**
 - OS: Windows 11 Pro
  - 22H2 10.0.22621 Build 22621

**Comment by amakvana** [comment]
Definitely a false positive.

https://www.virustotal.com/gui/file/f5210703d567eac4ba7e31419b59b5fe65dd9f97117ac8c029223c9f6f705694

**Comment by Kroissan** [comment]
![image](https://github.com/amakvana/EzYuzu/assets/66138267/34330075-df3b-408b-8945-ea7f822ab5d1)
Same flagged before download even finished 

Version	10.0.22621 Build 22621

**Comment by amakvana** [comment]
Click on Actions and allow. It's a false positive

**Comment by amakvana** [comment]
Closed - Windows Defender has picked up EzYuzu as a false positive. A copy of EzYuzu 1.6.1.0 has been sent to Microsoft to add into their heuristics.

These are the URL's EzYuzu connects to

**App Version Checking (checks if EzYuzu is latest version):**
https://raw.githubusercontent.com/amakvana/EzYuzu/master/version

**Json Data:**
https://api.github.com/repos/pineappleEA/pineapple-src/releases
https://api.github.com/repos/yuzu-emu/yuzu-mainline/releases

**Dependencies:**
https://raw.githubusercontent.com/amakvana/EzYuzu/master/assets/7z/22.01/7z.zip
https://aka.ms/vs/16/release/vc_redist.x64.exe

VirusTotal reports back as safe

https://www.virustotal.com/gui/file/c7bf833d7f066ee1e041ecd106d8a832f2716e0e04cdd038586146b179f64024?nocache=1
