### ISSUE TITLE
backup saves each time the app possibly can

### ISSUE THREAD

**Issue by Anatharias** [amakvana/EzYuzu#29]
Title basically. too many people are loosing their saves because of random actions. having an utility like this backing up saves would be enormous!

**Comment by amakvana** [comment]
Okay fair enough! I can programmatically zip the save data folders.

Where do you suggest the zipped archived be stored? User choice? Within %appdata% somewhere? Or ...

**Comment by Metroid-Prime** [comment]
@amakvana  User choice is best.   Portable is the preferred way for most people!

**Comment by amakvana** [comment]
Closed - Yuzu Project has ended
