### ISSUE TITLE
Steam Deck compatibility 

### ISSUE THREAD

**Issue by DabesDas** [amakvana/EzYuzu#30]
Not sure if it's possible, but is there a way to get this app functioning on the Steam Deck? 

I know there's a plugin named Decky Loader that has been used for extra Deck functionality - I wonder if this would be compatible.

**Comment by amakvana** [comment]
At the moment, despite it running on .NET 7, EzYuzu uses Windows Forms as the underlying UI platform which isn't compatible with Linux.

I am currently in the process of rewriting another app I'm developing, [YuzuModDownloader](https://github.com/amakvana/YuzuModDownloader), to support Linux/SteamOS using AvaloniaUI as the base for the UI. At the moment I am ironing many bugs that have occurred while rewriting the app, but there is major progress.

Once I am happy with the rewrite of YuzuModDownloader and release it, I will then look to rewrite EzYuzu using AvaloniaUI as the UI platform to support Linux/SteamOS.

For now, I shall keep this open until completed

**Comment by DabesDas** [comment]
Wow, that sounds amazing. Thank you so much your your efforts!   
  

  

  

  
  
  
  
  
>

**Comment by Redhawk18** [comment]
> At the moment, despite it running on .NET 7, EzYuzu uses Windows Forms as the underlying UI platform which isn't compatible with Linux.
> 
> I am currently in the process of rewriting another app I'm developing, [YuzuModDownloader](https://github.com/amakvana/YuzuModDownloader), to support Linux/SteamOS using AvaloniaUI as the base for the UI. At the moment I am ironing many bugs that have occurred while rewriting the app, but there is major progress.
> 
> Once I am happy with the rewrite of YuzuModDownloader and release it, I will then look to rewrite EzYuzu using AvaloniaUI as the UI platform to support Linux/SteamOS.
> 
> For now, I shall keep this open until completed

why would you write these tools in c# to begin with? c# is a vendor lock in at the language level.

**Comment by amakvana** [comment]
Closed - Yuzu Project has ended
