### ISSUE TITLE
Start button next to update button so we can use it as a launcher without having to install latest update

### ISSUE THREAD

**Issue by cufish** [amakvana/EzYuzu#31]
Currently the only way to have yuzu start is by updating or enabling auto start, but it would be handy if there would be a start button next to the update button so we can freely change versions/update channels and then launch yuzu all from 1 shortcut. Also opening EzYuzu when having the latest version installed with the auto update toggle on makes it impossible to change update channels/install an older build without deleting the version file.

**Comment by amakvana** [comment]
Thanks for opening up an issue.

<br>

> Currently the only way to have yuzu start is by updating or enabling auto start, but it would be handy if there would be a start button next to the update button so we can freely change versions/update channels and then launch yuzu all from 1 shortcut.

I'm not quite sure what you mean, so this is how I have interpreted this (correct me if I am wrong):

You'd like the ability to launch Yuzu after you've changed versions / update channels? If so, toggling the "Launch Yuzu" option would achieve this as the only way to change channels/versions is pulling a copy through, so you'd have to click on the "Update" button to do this?

Alternatively, you could use the [Command Line Options](https://github.com/amakvana/EzYuzu/blob/master/GUIDE.md#command-line-interface-options) to create two shortcuts, one changing the branch to mainline and launching Yuzu, the other changing branch to EA and launching Yuzu 

Correct me though if I have misinterpreted

<br>

> Also opening EzYuzu when having the latest version installed with the auto update toggle on makes it impossible to change update channels/install an older build without deleting the version file.

I shall look into this and see what I can do

**Comment by cufish** [comment]
I worded that really awkward, my bad.

What I mean is that currently if you have it set to autoupdate/start yuzu there is no way to install a different version when you're on the latest because it'll just instantly launch yuzu.

That's why it would be handy if besides having the autolaunch option there would just be a button next to install/update that launches yuzu. This way you could open Ezyuzu, decide if you want to keep the latest version or downgrade/swap to different branch and then launch.

**Comment by amakvana** [comment]
Apologies for the late response, thanks for clearing that up!

I am currently working on a feature that allows EzYuzu to be launched in a "Safe Mode" state, with all options being set as "Factory Defaults" - bypassing any saved options which should allow overriding the GUI without being in a position where EzYuzu auto-launches 

Something discussed here https://github.com/amakvana/EzYuzu/issues/36

Let me know your thoughts!

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.2.0
https://github.com/amakvana/EzYuzu/releases/latest
