### ISSUE TITLE
Change the "Update to Yuzu [version]" label on the button to "Update from [current version] to [new version]"

### ISSUE THREAD

**Issue by mateohhh** [amakvana/EzYuzu#35]
Totally minor, optional thing, but for would be good for clarity, especially if you have multiple test portables going. The interface doesn't mention the current version installed at all.

**Comment by amakvana** [comment]
Hey! Apologies for the delayed reply 

Sure thing! I shall tweak the text displayed on the button to reflect this, along with the current branch being updated

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.2.0
https://github.com/amakvana/EzYuzu/releases/latest
