### ISSUE TITLE
3 second time out before closing and opening up Yuzu

### ISSUE THREAD

**Issue by buthig666** [amakvana/EzYuzu#36]
**Is your feature request related to a problem? Please describe.**
When there isn't an update and Ez is set to close and open Yuzu, It is impossible to get to the menu tabs before Ez closes.
**Describe the solution you'd like**
Maybe a 3 second wait period before closing and opening up Yuzu, so one could have a moment to click on the settings tab?
**Describe alternatives you've considered**
Idk maybe a right click option to get to the settings or override the update auto close/open function?
**Additional context**
Thank you so much for this functional little program, especially now that Yuzu is updating multiple times per day and a certain Game that rhymes with "Beers of the Random" is seeing daily improvements because of it.  Very convenient.

**Comment by amakvana** [comment]
Hey! Thanks for opening up the issue, apologies for the delayed reply 

I am thinking of integrating a feature whereby it can launch EzYuzu into a "Safe Mode" state, which bypasses saved options, allowing the user to then open and reset EzYuzu accordingly 

Potentially something like holding the `SHIFT/CTRL` key before launching EzYuzu, similarly to how Microsoft Word does it with the `CTRL` key

**Comment by RobbyMeeker** [comment]
> Hey! Thanks for opening up the issue, apologies for the delayed reply
> 
> I am thinking of integrating a feature whereby it can launch EzYuzu into a "Safe Mode" state, which bypasses saved options, allowing the user to then open and reset EzYuzu accordingly
> 
> Potentially something like holding the `SHIFT` or `CTRL` key before launching EzYuzu, similarly to how Microsoft Word does it with the `CTRL` key

That's a great idea, better than implementing a delay in my opinion.

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.2.0
https://github.com/amakvana/EzYuzu/releases/latest
