### ISSUE TITLE
Integration 7-Zip to EzYuzu

### ISSUE THREAD

**Issue by harlayzhou** [amakvana/EzYuzu#37]
Integration 7-Zip to EzYuzu, don't needed download 7-Zip everytime.

**Comment by amakvana** [comment]
Hey! 

I haven't found a decent 7-Zip wrapper that I can reliably use for NET 7. However, I am open to suggestions.

For now, until a suitable wrapper / package has been identified, EzYuzu does a couple of checks regarding 7-Zip

1. If 7-Zip is installed on the machine, EzYuzu will use the installed copy and skip downloading a remote copy 
2. If check 1 fails, EzYuzu checks if 7-Zip has been previously downloaded by itself and the user has not deleted that copy. If the previously downloaded 7-Zip executable exists, EzYuzu will use that and skip downloading another copy

If both checks above fail, a fresh copy of 7-Zip is downloaded

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.2.0
https://github.com/amakvana/EzYuzu/releases/latest
