### ISSUE TITLE
Command line for updating silently

### ISSUE THREAD

**Issue by LegzRwheelz** [amakvana/EzYuzu#38]
Hi, as the title suggests, I would love to see support for command line arguments for silently updating. 

**Describe the solution you'd like**
Some kind of command line implementation for updating Yuzu silently through CMD or PowerShell. Ideally, this would be used to create a task in task scheduler in Windows.
Another idea would be to have an option to run at system start and have it quietly check for updates from the system tray with the ability to tell it how frequently we want it to check for updates (hourly, daily, weekly, bi-weekly, monthly). Maybe offering options for both. ie: creating a task in task scheduler and/or running from the system tray. 

**Additional context**
I am among the many users of the amazing frontend, LaunchBox. Use LaunchBox users tend to automate nearly everything to keep the computer as appliance-like as possible whine letting our emulators up-to-date while using LaunchBox I use it as the shell for our PCs (instead of Windows explorer) and we only have gamepads out arcade sticks connected for navigation of the system and only use a kb/m for servicing the emulators etc. Well due to the age of Yuzu and it frequently being updated and it's performance ever increasing, we need to keep LB as up-to-date as possible but it kinda kills the appliance-like experience and creates additional windows for downtime. So being able to keep it automatically as well as silently updated, would be a great feature to have and would placate a somewhat large group of users and is something I think all Yuzu users would welcome. (Instead of using the maintenance tool, which cannot be programmed to automatically update or even be ran from CMD/PowerShell or any scripting language that I've found)

**Comment by amakvana** [comment]
Thanks for opening up this issue.

EzYuzu does support [Command Line Options](https://github.com/amakvana/EzYuzu/blob/master/GUIDE.md#command-line-interface-options) natively. The [User Guide](https://github.com/amakvana/EzYuzu/blob/master/GUIDE.md) also has some [usage examples](https://github.com/amakvana/EzYuzu/blob/master/GUIDE.md#usage-examples) too

You can use these to create Task Scheduler tasks to automate updating silently. 

Let me know if this achieves the goal you are looking for. If not, let me know some suggestions to make with the Command Line Options and I can look to implement them. 

Cheers

**Comment by LegzRwheelz** [comment]
This is cool and looks promising. I wish I had found it before commenting :/ I will test in just a min and report back to suggest anything additional. Thank you

**Comment by amakvana** [comment]
That's exactly how it should behave. There won't be any user feedback, but it will close out automatically. You can confirm the update has been successful by opening the file called `version` and checking the number inside it.

I have multiple builds of Yuzu on my PC, so I have created a Batch Script that does the updating for me. Here's my script, with amended paths.

```
@ECHO OFF 
CD /D "%~dp0"
START "" /WAIT "EzYuzu.exe" -p "D:\Yuzu-Builds\Auto"
START "" /WAIT "EzYuzu.exe" -p "D:\Yuzu-Builds\Forced-Mainline" -m
START "" /WAIT "EzYuzu.exe" -p "D:\Yuzu-Builds\Forced-Mainline" -e
EXIT /B 0
```

The script lives inside the same folder where EzYuzu resides. I also then add one Task inside Task Scheduler, which points to this script, to do weekly updates.

**Comment by LegzRwheelz** [comment]
Thank you very much for your brilliant mind and awesome work! I am very pleased with this. So much so I would like to buy you a coffee....will you allow me to buy you a coffee?

**Comment by amakvana** [comment]
> Thank you very much for your brilliant mind and awesome work! I am very pleased with this. So much so I would like to buy you a coffee....will you allow me to buy you a coffee?

Anytime! 

I haven't set up any Donations as such yet, as I just haven't had the time to do so - life isn't being kind atm. However, I will set something up during this week and post back in here.

Thank you so much thought, it's really appreciated!

I'll leave this open until I post back in here :)

**Comment by LegzRwheelz** [comment]
Ofc, I hope things settle down for you, I will say a prayer for you tonight... and just remember the old saying "This too, shall pass"....it always does. Keep ya head up, I am rooting for ya and look forward to getting to buy you a coffee or 5 🤭

**Comment by amakvana** [comment]
> Ofc, I hope things settle down for you, I will say a prayer for you tonight... and just remember the old saying "This too, shall pass"....it always does. Keep ya head up, I am rooting for ya and look forward to getting to buy you a coffee or 5 🤭

Apologies for the delayed response! Donation options have now been added
