### ISSUE TITLE
Change the Browse For Folder Window

### ISSUE THREAD

**Issue by Naworm** [amakvana/EzYuzu#4]
Change the Browse For Folder Window

Use everything else but this (since you can't copy/paste in here):
![image](https://user-images.githubusercontent.com/48997616/128646264-edf866dc-c4e3-4056-a656-fc1bfb5edac1.png)

This one is much much better ;)
![image](https://user-images.githubusercontent.com/48997616/128646313-b3508615-f81d-4b18-b28b-58a83ccf8dab.png)

**Comment by amakvana** [comment]
Thanks! In the next revision which should be coming soon, I've got some updates with the Browsing functionality. Juggling two jobs so time is rare at the moment haha!

**Comment by amakvana** [comment]
This has now been implemented in v1.2.0.0

https://github.com/amakvana/EzYuzu/releases/latest
