### ISSUE TITLE
Add option to automatically rename yuzu.exe to cemu.exe for HDR support on Windows 11

### ISSUE THREAD

**Issue by bannert1337** [amakvana/EzYuzu#40]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is indeed related to a problem. As a user of Windows 11, I find that HDR support is not readily available for `yuzu.exe` in the open-source application. This creates a disconnect in the overall user experience as Windows 11 natively supports HDR, but this cannot be leveraged effectively due to the lack of support within `yuzu.exe`.

**Describe the solution you'd like**
I propose an automatic renaming option for `yuzu.exe` to `cemu.exe`. Windows 11 recognizes `cemu.exe` for HDR support and this would be a simple and straightforward solution to implement. This feature could be added to the settings of the open-source app, enabling users to toggle on or off the automatic renaming feature as required. 

**Describe alternatives you've considered**
A couple of alternatives come to mind:

1. Manual renaming: Though currently feasible, it is inconvenient as it requires users to remember to do so each time they want to take advantage of the HDR support.

2. Engaging with Microsoft to include `yuzu.exe` in their list of applications that can leverage HDR. While this might be the ideal solution, it may take a longer time and the outcome isn't guaranteed.

**Additional context**
HDR support is an essential feature for many users today and its lack of support can result in a sub-optimal user experience. The proposed solution should be relatively easy to implement and would provide immediate benefits to Windows 11 users, while we explore other long-term solutions.

**Comment by amakvana** [comment]
Thanks for opening up the issue! Sure thing, I can add some logic to rename the executable. I'll also incorporate an option to enable/disable this feature too

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.2.0
https://github.com/amakvana/EzYuzu/releases/latest
