### ISSUE TITLE
Doesnt work anymore, unhandeled exception

### ISSUE THREAD

**Issue by mato200** [amakvana/EzYuzu#41]
https://imgur.com/a/VMd6qwl
win11, all dependecies installed
it happens when i select the Yuzu path

it worked 3 days ago....

**Comment by amakvana** [comment]
Thanks for opening up the issue, would you be able to recreate the error and post the full error log?

So copy and paste the entire log beginning from "See the end of this message for the details invoking...."

**Comment by mato200** [comment]
literally nothing changed in the meanwhile, and now it works
