### ISSUE TITLE
Looking to collaborate with the dev

### ISSUE THREAD

**Issue by LegzRwheelz** [amakvana/EzYuzu#42]
**Is your feature request related to a problem? Please describe.**
No, this is no related to a problem per se. This is an idea and would like to talk in private with the dev on maybe branching this tool into a tool for other emulators. I am very new to writing code/dev apps apart from AutoHotKey and a few other scripting languages but want to do this and give back to the community and figure talking with the dev would be a great start. Unfortunately, I am unsure of how I would go about connecting. I don't want to put my email or Discord handle out here for the public so I figure with this, I can reach out and you can decide if you are interested and can decide the best way to conncet.

**Describe the solution you'd like**
Talking in private, lol

**Additional context**
So after discovering the beauty of using this tool to update Yuzu silently as a task in task scheduler, I decided to search for tools like this for other emulators. Even though many emus offer updating within the program, in my use case (launching games from launchbox) it is not ideal as I don't keep a KB/M attached to my HTPC. I found one for Xenia emu and asked the dev to implement silent update switches and he went on to make a .net CLI tool which works great. I decided to try editing the source code to use it to update Xemu emulator and that half butt works. The biggest problem I have is it shows a console window when it is ran, the other issue is that this tool only works when the LICENSE.txt file is deleted. So, I want to make a few different updaters (using your source code for a base) for all the emus I use and release them for the people in my same use case.

I look forward to hearing back from you.

**Comment by buthig666** [comment]
I believe the Dev's name is u/ConsistentHornet4  on reddit.

**Comment by amakvana** [comment]
Apologies for the late response! What's your thoughts? @LegzRwheelz. I'm pretty open for collaborating :)

**Comment by amakvana** [comment]
This issue has been closed because there has been no response to our request from the original author. With only the information that is currently in the issue, we don't have enough information to take action.

Please reach out if you have or find the answers we need so that we can investigate further.

Thanks!
