### ISSUE TITLE
Yuzu arguments passthrough

### ISSUE THREAD

**Issue by Lucide** [amakvana/EzYuzu#47]
It would be useful to support passing arguments to the yuzu executable,
for example, in the case yuzu is ran from a launcher with `-f -g "{ImagePath}"`.

Usually this is handled with a special parameter which takes all the remaining arguments and passes
them down to the executable. Other tools use `--`, although that brings up a [common pitfall](https://stackoverflow.com/questions/15780174/powershell-command-line-parameters-and) in windows Powershell.

**Comment by amakvana** [comment]
I had never even considered this! Would be very useful. So something like this? 

`start "" /wait "EzYuzu.exe" -p "D:\Yuzu" -f -g "D:\Games\Game.xci"`

Essentially update Yuzu to the latest version, then automatically run the selected game in fullscreen?

**Comment by Lucide** [comment]
Yes, but with some way to distinguish between EzYuzu args and yuzu's.

I'm not sure "pass down all unrecognised arguments" is sufficient because eventually yuzu might introduce clashing arg names.

**Comment by amakvana** [comment]
Closed - Yuzu Project has ended
