### ISSUE TITLE
Support manually set a proxy for updating yuzu

### ISSUE THREAD

**Issue by BLumia** [amakvana/EzYuzu#48]
**Is your feature request related to a problem? Please describe.**
In some regions, it can be slow to access sites like GitHub, thus the download speed of using EzYuzu to update Yuzu will be quite slow. A HTTP or Socks5 proxy can be used to speedup downloading, but users usually won't want to set a system-level proxy if they only want a specific app to use the proxy.

**Describe the solution you'd like**
Add an option to allow set a http or socks5 proxy manually. It could have the following options:

1. Proxy type: Follow System / HTTP / Socks5
2. Host
3. Port

**Describe alternatives you've considered**
It could be good if the app can support both HTTP and socks5, but only HTTP or socks5 is also okay,

**Additional context**
`ssh -D` can be used to set up a simple socks5 server which can be much easier for testing. Other proxy tools could work as well.

**Comment by amakvana** [comment]
Never realised that was the situation in some regions. I'll add support for that within EzYuzu.

In the meantime, you can use a Batch Script to toggle the Proxy Server before running EzYuzu via command line. So something like this:

```
@echo off 

set "proxyUrl=contoso.com"
set "proxyPort=1234"
set "yuzuPath=D:\Yuzu"

REM ===== DO NOT MODIFY BELOW THIS LINE ===== 
cd /d "%~dp0"
echo(Backing up current proxy settings ...
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v "ProxyEnable"') do set "oldProxyEnable=%%a"
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v "ProxyServer" /t REG_SZ ^| findstr "REG_SZ"') do set "oldProxyServer=%%a"
echo(Changing proxy to %proxyUrl%:%proxyPort% ...
>nul 2>&1 reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v "ProxyEnable" /t REG_DWORD /d "1" /f
>nul 2>&1 reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v "ProxyServer" /t REG_SZ /d "%proxyUrl%:%proxyPort%" /f
>nul 2>&1 timeout /t 01 /nobreak 
echo(Running EzYuzu ... 
start "" /wait "EzYuzu.exe" -p "%yuzuPath%"
echo(Restoring old proxy settings ...
>nul 2>&1 timeout /t 01 /nobreak
>nul 2>&1 reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v "ProxyEnable" /t REG_DWORD /d "%oldProxyEnable%" /f
>nul 2>&1 reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v "ProxyServer" /t REG_SZ /d "%oldProxyServer%" /f
```

Modify the 2nd and 3rd line to match your Proxy Server Address and Proxy Server Port.
Modify the 4th line to point to where your copy of `yuzu.exe` resides.

Save the script above as "LaunchEzYuzuWithProxy.bat" and place it inside the same folder where your `EzYuzu.exe` resides.

Run the script and it should then do this, in order:
1. Backup your current proxy settings
2. Set the proxy to what is specified on line 2 and 3 
3. Run EzYuzu and update your copy of Yuzu specified on line 4
4. Restore your old proxy settings 

Let me know how you get on.

**Comment by amakvana** [comment]
Closed - Yuzu Project has ended
