### ISSUE TITLE
Forcefully shuts down windows when attempting install, puts computer in Repair loop when external drive still plugged in.

### ISSUE THREAD

**Issue by Collcroc123** [amakvana/EzYuzu#5]
Everything in the title. Plugged in an external SSD, created a folder for yuzu, opened EzYuzu, selected the location, selected New Install in the dropdown, clicked install, and my PC was forcefully restarted a few seconds later. When my PC tried to reboot, it would get stuck in an Automatic Repair loop, until I unplugged the drive when it finally exited the loop. Tried it multiple times, happened multiple times.

**Comment by amakvana** [comment]
Apologies! 

Microsoft have recently made changes to their C++ Redistributable installer, which now forces reboots. I have some solutions I am currently testing at the moment, once I am happy with the tests and outcomes, I will push a new version out which should rectify the issues.

Just juggling two jobs at the moment so time is a little parse, but bear with me.

**Comment by amakvana** [comment]
This should now be resolved in v1.2.0.0

https://github.com/amakvana/EzYuzu/releases/latest

If this has resolved the rebooting issue, let me know & I shall close this
