### ISSUE TITLE
App Crashing on 1.2.0.0

### ISSUE THREAD

**Issue by Naworm** [amakvana/EzYuzu#6]
App Crashing on 1.2.0.0
![2021-08-21 12_47_14-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/48997616/130323866-d501e4c4-dd32-43c4-93e2-79c9ebed910b.png)

**Comment by amakvana** [comment]
Just tried the same options as you and I'm unable to reproduce the error. Delete the "yuzu-windows-msvc" folder and try again.

Check that your antivirus hasn't flagged up the Yuzu directory.

**Comment by Naworm** [comment]
Seem's ok after cleanup, but I will retry on next update to make sure
