### ISSUE TITLE
No EzYuzu.exe

### ISSUE THREAD

**Issue by yuty89** [amakvana/EzYuzu#9]
The github download does not have the EzYuzu.exe file

**To Reproduce**
1: go to https://github.com/amakvana/EzYuzu
2: no EzYuzu.exe
3: go insane trying to figure out the instructions without having the .exe

**Expected behavior**
Having the .exe

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by amakvana** [comment]
Click on the "Releases" section on the right sided column, or it can be found using the link below:
https://github.com/amakvana/EzYuzu/releases/latest

Download EzYuzu.zip and extract the contents of it

**Comment by yuty89** [comment]
Thank you very much

Resolved.
